# Generated by Django 5.2.9 on 2025-12-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='status_curso',
            new_name='status',
        ),
    ]
